server:
  port: 10005

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  db:
    driver: org.mariadb.jdbc.Driver
    username: root
    password: toor
    url: jdbc:mariadb://localhost:3306/k8sorder

########### EUREKA ###########
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  fetch-registry: true
  register-with-eureka: true